---
- name: the main playbook to be executed 

  vars_files:
    - vars_defaults.yml
    - vars_aws_config.yml
    # HOST_TO_REPLACE: 

  hosts: "{{HOST_TO_REPLACE}}"
  gather_facts: true
  become: true


  tasks:
      
  # block to install dependencies for aws in remote host  
  # block to save the instance-id for the target instance   
   - block:
       - name: check/install python3 and pip on the server
         apt:
           update_cache: yes
           state: present 
           name: [python3, python3-pip]

       - name: install boto3 using pip 
         pip: 
           name: boto3
           state: present
      
       - name: get instance-id using get aws meta-url
         uri: 
           url: "http://169.254.169.254/latest/meta-data/instance-id"
           return_content: yes 
         register: res_instance_id
       - set_fact:
           target_instance_id: "{{ res_instance_id.content  }}"   
       
       - debug: msg="target instance-id is  {{  target_instance_id  }}"

     rescue:
       - debug:
           msg: 'Error in install + get instance id block'


    # block to collect information of aws ec2 instance   
   
   - block:
       - name: collect facts about the instance using ec2 module and save it
         ec2_instance_facts:
           aws_access_key: "{{  AWS_ACCESS_KEY  }}"
           aws_secret_key: "{{  AWS_SECRET_KEY  }}"
           region: "{{  AWS_REGION  }}"
           instance_ids: ["{{  target_instance_id  }}"]       
         register: res_instance
       - set_fact:
           instance_meta: "{{  res_instance.instances[0]  }}" 

      # - name: save target ec2 facts to instance_facts.yml file in local machine 
       - copy:
           content: "{{ instance_meta | to_yaml }}"
           dest: "{{  OUTPUT_DIRECTORY  }}/instance_facts.yml"
     
     connection: local
     become: False
     run_once: True 
     rescue:
       - debug:
           msg: 'Error in collect facts block'


    # STEP-2 B: copy the keys file from the target host to local machine. 
    # block to copy keys from remote host to control machine  
   - block:
       - name: copy the authorized_keys file to outputs directory -> executing in remote host
         fetch:
           src: ~/.ssh/authorized_keys
           dest: "{{  OUTPUT_DIRECTORY  }}/authorized_keys"
           flat: yes

     become: False
     run_once: True
     rescue:
       - debug:
           msg: 'Error in copying authorized_keys file to outputs directory' 
   

   # launch a new ec2 with configuration of old instance  
   - block:
       - name: launch a new ec2 instance using the target host configuration 
        # below are temporary varaibles to create list. (optimization possible)
         vars:
           sec_groups: []         
     
         set_fact:
           sec_groups: "{{ sec_groups }} + [ '{{ item.group_id }}' ]"
           iam_role_attach:  "{{  instance_meta.iam_instance_profile.arn.split('/')[1]  }}"
         loop:
           "{{ instance_meta.security_groups }}"

      #  launch a new ec2 and wait
   
       - ec2:
           aws_access_key: "{{  AWS_ACCESS_KEY  }}"
           aws_secret_key: "{{  AWS_SECRET_KEY  }}"
           region: "{{  AWS_REGION  }}"

        #  this is base it will work for sure withot errors
           instance_type: "{{  instance_meta.instance_type }}"
           image: "{{  instance_meta.image_id }}"
           vpc_subnet_id: "{{  instance_meta.subnet_id }}"
           zone: "{{ instance_meta.placement.availability_zone }}"
           key_name: "{{  DEFAULT_EC2_KEY_PAIR  }}"                    #keypair
         
        # yes and no keys 
           assign_public_ip: yes
           wait: yes
     
        # below keys need to be first formatted before use. (may cause errors) needs exception handling 
           instance_profile_name: "{{  iam_role_attach  }}"
           instance_tags: "{{ instance_meta.tags | from_yaml }}"
           group_id: "{{ sec_groups | to_json | from_yaml }}"          
         register: ec2_launch_output       
       - set_fact:
           launched_meta: "{{  ec2_launch_output.instances[0]  }}" 

        # debug code for dev use 
       - copy:
           content: "{{ instance_meta | to_yaml }}"
           dest: "{{  OUTPUT_DIRECTORY  }}/launch_instance_facts.yml"
       - debug:
           msg: "Launch Output:  {{ instance_meta }}"     

     connection: local
     become: False
     run_once: True   
     rescue:
       - debug:
           msg: 'I caught an error, while launching a new ec2 instance :-)'
          
     # this block saves the new key to local system before ssh   
  #  - name: block executing in local machine as un-privileged user
  #    block:
  #    - name: add keys to ansible control machine 
  #      shell: | 
  #             chmod 400 '{{ KEY_PAIR_PATH }}'
  #             eval `ssh-agent`
  #             ssh-add '{{ KEY_PAIR_PATH }}'
  #      register: output_key
  
  #    - debug: msg="response {{output_ke}}"
  #   #  delegate_to: "{{lookup('env','USER')}}"
  #    connection: local
  #    become: False
  #    run_once: True 
  #    rescue:
  #      - debug:
  #          msg: 'above block is having error -- ssh add error  {{output_key}} :-)'


  #  - pause:
  #      seconds: 120

    # copy authorized_key files to the new host using ip
  #  - name: block executing in local machine as un-privileged user
  #    block:
  #    - name: copy the target host authorized_keys to new launched instance 
  #      copy:
  #        src: "{{ OUTPUT_DIRECTORY }}/authorized_keys"
  #        dest: ~/.ssh/authorized_keys
     
  #    become_user: ubuntu
  #    delegate_to: "{{ launched_meta.public_ip }}"
  #    run_once: True 
  #    rescue:
  #    - debug:
  #        msg: 'error in copying keys to the remote new host, :-)'







...